# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [ ]:
# Tu respuesta aquí
nombre = "Yuly"
edad = 26

print ("Hola, me llamo", nombre, "y tengo", edad, "años")

Hola, me llamo Yuly y tengo 26 años


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [ ]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí
print (numeros[0], numeros [5])
print (numeros[:3])
numeros.append(99) #se usa la función .append() para agregar valores a una lista
print(numeros)

10 15
[10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [ ]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"] >= 6:
  print ("Aprobado")
else:
  print ("Reprobado")


Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [ ]:
# Tu respuesta aquí
def calcular_area(base, altura):
    return (base * altura) / 2

resultado = calcular_area(5, 8)
print(resultado)

20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [ ]:
from typing_extensions import List
# Tu respuesta aquí
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] #Definimos la variables que contiene los numeros del 1 al 10

cuadrados = [x**2 for x in num] #Creamos la lista de compresión
print (num, "\n", cuadrados)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
 [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [ ]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [ ]:
# Tu respuesta aquí
num_decimales = np.array([1.5, 2.5, 3.5, 4.5])
matriz_zeros = np.zeros((3,4))
arreglo = np.linspace(0 , 10, 6)

print("Números decimales:", num_decimales, "\n")
print("Matriz de ceros: \n", matriz_zeros, "\n")
print("Arreglo:",  arreglo, "\n")


Números decimales: [1.5 2.5 3.5 4.5] 

Matriz de ceros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Arreglo: [ 0.  2.  4.  6.  8. 10.] 



**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [ ]:
a = np.arange(1, 13)

# Tu respuesta aquí

matriz = a.reshape(3, 4)

print("Matriz\n", matriz, "\n")
print("Valor máximo:", np.max(a))
print("Valor mínimo:", np.min(a))

#Indice del número máximo en la lista
index_max= np.argmax(matriz)

#Coordenadas del índice
posicion= np.unravel_index(index_max, matriz.shape)

print("Posición:", posicion)

Matriz
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Valor máximo: 12
Valor mínimo: 1
Posición: (np.int64(2), np.int64(3))


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [ ]:
# Tu respuesta aquí
arreglo1 = np.random.randint(1, 20, 5)
arreglo2 = np.random.randint(1, 20, 5)

suma = arreglo1 + arreglo2
resta = arreglo1 - arreglo2
multiplicacion = arreglo1 * arreglo2

print("Arreglo 1:", arreglo1)
print("Arreglo 2:", arreglo2)

# Operaciones
print("\nSuma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)

Arreglo 1: [14  4  6 17  3]
Arreglo 2: [ 1  2  8  3 17]

Suma: [15  6 14 20 20]
Resta: [ 13   2  -2  14 -14]
Multiplicación: [14  8 48 51 51]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [ ]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
notas_mayores_igual_6 = notas[notas >= 6]

print("Notas mayores o iguales a 6:", notas_mayores_igual_6)



Notas mayores o iguales a 6: [ 8.5  6.   9.2  7.8 10. ]
